export { classifyIntent, shouldProposeSkill, generatePatternDescription } from './cognitive-router'
export { processInteraction, continueAfterApproval, rejectInteraction } from './pipeline-orchestrator'
export { executeCognitiveRequest, streamCognitiveRequest } from './CognitiveAdapter'
export type { CognitiveResult } from './CognitiveAdapter'
export { compileArchitecture, FOUNDRY_SYSTEM_PROMPT } from './foundry-compiler'
